language: node_js
node_js:
  - "node"
script:
  - npm run test:unit

before_deploy:
  - npm run build

deploy:
  provider: pages
  local-dir: dist/
  skip_cleanup: true
  keep_history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master

cache:
  directories:
    - "node_modules"
