language: node_js
node_js:
  - "10"
script:
  - npm run test:unit

before_deploy:
  - npm run build
  - cp -R coverage ./dist/

deploy:
  provider: pages
  local-dir: dist/
  skip_cleanup: true
  keep_history: true
  github-token: $GITHUB_TOKEN
  on:
    branch: stable

cache:
  directories:
    - "node_modules"
